main: com.winthier.itemstore.ItemStorePlugin
name: ItemStore

version: 0.1
api-version: '1.21.11'

description: Store and load serialized items
author: StarTux
website: https://cavetale.com

depend: []
commands:
  storeitem:
    description: Store an item
    usage: /<command> <name>
    permission: itemstore.store
  loaditem:
    description: Load an item
    usage: /<command> <name>
    permission: itemstore.load
permissions:
  itemstore.store:
    default: op
  itemstore.load:
    default: op
